import { StateGraph, StateSchema, type GraphNode, START, END } from "@langchain/langgraph";
import z from 'zod';
import { gemini, mistral, cohere } from "./model.service.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

//Provider strategy us only used for google models present in langchain and for other we have to use key strategy;

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
      solution_1_score: z.number().default(0),
      solution_2_score: z.number().default(0),
      solution_1_reasoning: z.string().default(""),
      solution_2_reasoning: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof state> = async (state)=>{
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistral.invoke(state.problem),
    cohere.invoke(state.problem)
  ])
  return{
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text
  }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const judge = createAgent({
        model: gemini,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })}