import { StateGraph, StateSchema, type GraphNode, START, END, type CompiledStateGraph } from "@langchain/langgraph";
import z from 'zod';
import { gemini, mistral, cohere } from "./model.service.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

//Provider strategy us only used for google models present in langchain and for other we have to use key strategy;

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
      solution_1_score: z.number().default(0),
      solution_2_score: z.number().default(0),
      solution_1_reasoning: z.string().default(""),
      solution_2_reasoning: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof state> = async (state)=>{
  console.log("SOLUTION NODE STARTED!!")
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistral.invoke(state.problem),
    cohere.invoke(state.problem)
  ])
  return{
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text
  }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
  console.log("JUDGEMENT STARTED!!")
    const { problem, solution_1, solution_2 } = state

    const judge = createAgent({
        model: gemini,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })
  
    const judgeResponse = await judge.invoke({
      messages:[
        new HumanMessage(
          `Problem: ${problem} Solution 1: ${solution_1} Solution 2: ${solution_2} Please evaluate the solutions and provide scores and reasoning.`
        )
      ]
    })

    const {solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning} = judgeResponse.structuredResponse

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}

const graph = new StateGraph(state)  //State Graph is mianly used to create nodes adn edges to make a chain of connection between different nodes.
      .addNode("solution",solutionNode)
      .addNode("judge_node",judgeNode)
      .addEdge(START,"solution")
      .addEdge("solution","judge_node")
      .addEdge("judge_node",END)
      .compile();

export default async function (problem: string) { 

    const result = await graph.invoke({
        problem: problem
    })

    return result

}